### ISSUE TITLE
support shm_open and shm_unlink?

### ISSUE THREAD

**Issue by mjuned47** [termux/libandroid-shmem#10]
I had compile a library but error 
Undefined reference/symbol : shm_open
Undefined reference/symbol : shm_unlink

Using android ndk -r22

Or is there any way to use ashmem instead of shm? If yes then how to do it?

**Comment by ghost** [comment]
Have you tried exporting or specifying:

`LDFLAGS+=" -landroid-shmem"`?

**Comment by Grimler91** [comment]
You can add shm_open and shm_unlink functions to the library you are trying to compile, this is done for a [couple of packages](https://github.com/search?q=org%3Atermux+shm_open&type=code) in our repos. 

You might need to modify the configure script as well in case that looks for shm_open/shm_unlink and fails.

**Comment by mjuned47** [comment]
Much thanks, successfully build !
