### ISSUE TITLE
How to use this library for chroot?

### ISSUE THREAD

**Issue by Aloento** [termux/libandroid-shmem#2]
@fornwall How to use this library for chroot?

**Comment by Aloento** [comment]
I try to used
env LD_PRELOAD=“/path/to/libandroid-shmem.so”  chroot /rootfs /bin/su -l
But he told me, could not find the file or directory.
If I only use chroot /rootfs /bin/su -l ,will enter the system.
I am sure the library file directory is correct and given permission.

**Comment by Hax4us** [comment]
Why are using this before entering into chroot ? 
Its very easy and straight forward , just compile and export it under chrooted environment 
`export LD_PRELOAD=/path/to/blah blah.....`

**Comment by papuruth** [comment]
how to compile or can i use the already compiled file i.e. the libandroid-shmem.so file

**Comment by SDRausty** [comment]
I have tried every imaginable way, and the best I seem to get is: `sudo: error while loading shared libraries: liblog.so: cannot open shared object file: No such file or directory`

```
[root22:20home]$env LD_PRELOAD="/data/data/com.termux/files/usr/lib/libandroid-shmem.so" sudo
[root22:20home]$env LD_PRELOexport LD_PRELOAD="/data/data/com.termux/files/usr/lib/libandroid-shmem.so" sudo
[root22:22home]$sudo
sudo: error while loading shared libraries: liblog.so: cannot open shared object file: No such file or directory
```

Any suggestions on how to get the library to work are welcome.

**Comment by ghost** [comment]
Regarding use of libandroid-shmem in chroot'ed environments, answer is in https://github.com/termux/libandroid-shmem/issues/6#issuecomment-487723317 (in short: current version cannot be used).
