### ISSUE TITLE
liblog.so: cannot open shared object file

### ISSUE THREAD

**Issue by SDRausty** [termux/libandroid-shmem#3]
Shared memory appears to be important in many issues:

1) https://github.com/sdrausty/termux-archlinux/issues/4
2) https://github.com/sdrausty/TermuxArch/issues/38
3) https://github.com/sdrausty/TermuxArch/issues/55
4)  https://github.com/sdrausty/TermuxArch/issues/55https://github.com/sdrausty/TermuxArch/issues/59#issuecomment-381380567
4) https://github.com/sdrausty/TermuxArch/issues/68

Arch Linux in Termux PRoot:
```
[19:09 libandroid-shmem ]$ make
cc -fpic -shared -std=c11 -Wall -Wextra -Wl,--version-script=exports.txt  shmem.c -llog -o libandroid-shmem.so
shmem.c:1:10: fatal error: android/log.h: No such file or directory
 #include <android/log.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:4: libandroid-shmem.so] Error 1
[19:09 libandroid-shmem ]$ l android/log.h
-rw-r--r-- 1 e 4452 Nov 9 09:57 android/log.h
[19:09 libandroid-shmem ]$ cd test/ 
[19:11 test ]$ make
cc -Wall -Wextra -Werror -std=c99 -DSYSV_ASHMEM_TEST_SYSTEM error-codes.c -o test-error-codes
./test-error-codes
shmget: Permission denied
make: *** [Makefile:19: testcase-error-codes] Error 1
```
Termux:
```
[21:40 libandroid-shmem ]$ make install cc -fpic -shared -std=c11 -Wall -Wextra -Wl,--version-script=exports.txt shmem.c -llog -o libandroid-shmem.so
install -D libandroid-shmem.so /data/data/com.termux/files/usr/lib/libandroid-shmem.so
install -D shm.h /data/data/com.termux/files/usr/include/sys/shm.h
```
The Arch Linux in Termux PRoot sudo error has changed:
```
[23:16 data ]$ env LD_PRELOAD=/data/data/com.termux/files/usr/lib/libandroid-shmem.so startarch su user sudo
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: unable to load /usr/lib/sudo/sudoers.so: /usr/lib/sudo/sudoers.so: cannot stat shared object: Bad file descriptor
sudo: fatal error, unable to load plugins
[23:16 data ]$ env LD_PRELOAD=/data/data/com.termux/files/usr/lib/libandroid-shmem.so startarch l user
Welcome to Arch Linux in Termux!
Install a package: pacman -S package
More  information: pacman [-D|F|Q|R|S|T|U]h
Search   packages: pacman -Ss query
Upgrade  packages: pacman -Syu

Chat: https://gitter.im/termux
Help: info query and man query
IRC:  wiki.archlinux.org/index.php/IRC_channel

[23:17 ~ ]$ sudo
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: unable to load /usr/lib/sudo/sudoers.so: /usr/lib/sudo/sudoers.so: cannot stat shared object: Bad file descriptor
sudo: fatal error, unable to load plugins
[23:17 ~ ]$ env LD_PRELOAD=/data/data/com.termux/files/usr/lib/libandroid-shmem.so sudo
sudo: error while loading shared libraries: liblog.so: cannot open shared object file: No such file or directory
```

**Comment by SDRausty** [comment]
This issue is progressing with much effort, and slowly:
![screenshot_20180514-192546](https://user-images.githubusercontent.com/27742457/40029184-194e4402-57b1-11e8-850f-a8d105705901.png)

**Comment by sdrausty** [comment]
As far as is known, devices have two chips;  Hence, shared memory is out dated as far as modern devices are concerned.  Wrapper update requested.

**Comment by sdrausty** [comment]
Or put simpler, drop shmem. Purpose?

**Comment by sdrausty** [comment]
Since all memory is now in chip (ram) why even bother with shared memory?

**Comment by SDRausty** [comment]
Accessing libandroid-shmem support is now possibly in TermuxArch, use [`setupTermuxArch.sh r`](https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/files/stable/setupTermuxArch.sh) for quick system refresh; libandroid-shmem support is added with this https://github.com/sdrausty/TermuxArch/commit/a25067274c341b73d1fc79b85eabbbbdf33680eb commit.  The current version of TermuxArch also sets locales from Android in Arch Linux in Termux PRoot.

**Comment by SDRausty** [comment]
I have tried every imaginable way, and the best I seem to get is: `sudo: error while loading shared libraries: liblog.so: cannot open shared object file: No such file or directory`:
```
[root22:20home]$env LD_PRELOAD="/data/data/com.termux/files/usr/lib/libandroid-shmem.so" sudo
[root22:20home]$env LD_PRELOexport LD_PRELOAD="/data/data/com.termux/files/usr/lib/libandroid-shmem.so" sudo
[root22:22home]$sudo
sudo: error while loading shared libraries: liblog.so: cannot open shared object file: No such file or directory
```
Any suggestions on how to get the library to work are welcome.

**Comment by andymwat** [comment]
I'm having the same issue. I downloaded liblog.so from [https://github.com/innogames/android-ndk/blob/master/platforms/android-24/arch-arm64/usr/lib/liblog.so](here), but when I added it to my LD_PRELOAD path, the error changes to:
`/bin/sh: error while loading shared libraries: /usr/lib/aarch64-linux-gnu/libc.so: invalid ELF header
`
When I replace the libc.so in that folder with the one from that repository, it segfaults.

**Comment by ghost** [comment]
Regarding use of libandroid-shmem in chroot'ed environments, answer is in https://github.com/termux/libandroid-shmem/issues/6#issuecomment-487723317 (in short: current version cannot be used).
