### ISSUE TITLE
how complex would be to import yours library to Debian stable run by using Termux by using Proot?

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/libandroid-shmem#5]
Dear specialists,
How complex would be to port this library to ARMHF or ARM 64 architecture when I would like to use yourslibrary from Debian stable, which will be run by using Proot module for Termux?
Do you think, that it would be possible to create shared memory file or shared executable stack by using procedures and functions inside this .so library? Or this is too much and those techniques can not be supported with no recompiling and changing source code of Android kernel?
I wanted to run many various apps from Debian stable including gnome-session
KDE-plasma, but some C or C++ developers are using shared memory file creation techniques inside their apps, others are using shared executable stack creation.
Sure, there are many other apps, which do not use those techniques, including many text editors, even Audacity, and even Pulseaudio contain two variants of code for using normal memory pool instead of shared memory pool.
Thank you very much for yours answers.

**Comment by ghost** [comment]
This issue same as https://github.com/termux/libandroid-shmem/issues/2.
Closing.
