### ISSUE TITLE
Is it possible to use this library also while using chroot Linux environments which run by using Termux?

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/libandroid-shmem#6]
Dear specialists,
Is it possible to use this library also while running Debian, Ubuntu or other Termux scripts for Linux environment creation? Because many many apps, which have been developed not only by using C or C++ are using shared dynamic memory a nd other shared memory technology. How complex would be to allow users of Debian, Ubuntu and other distro which run by using Termux to use apps, which are using shared memory? Such as gnome-session, KDE and other complex apps, which are based on shared memory. The next example is postgressql which is also using this technique for working with memory.

**Comment by ghost** [comment]
No, unless it is patched.

For now, it relies on stuff provided exclusively by Android NDK headers and cannot be compiled against GNU libc which is typically used in Linux distributions.

Existing library (i.e. from Termux) cannot be used due to ABI incompatibility.
